services:
  Htpasswd\Security\HtpasswdUserProvider:
    class: Htpasswd\Security\HtpasswdUserProvider
    public: false
    arguments:
      - '%Htpasswd.path%'
      - '%Htpasswd.roles%'
  Htpasswd\Security\HtpasswdEncoder:
    class: Htpasswd\Security\HtpasswdEncoder
    public: false